# REMOVER isso (local)
# spring.datasource.url=jdbc:postgresql://localhost:5432/brincalibras
# spring.datasource.username=postgres
# spring.datasource.password=123

# NOVO (Neon)
spring.datasource.url=${postgresql://neondb_owner:npg_vOjIcp31EwCG@ep-still-dream-acf1qnm9-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect